version: "3.8"
services:
  mediawiki:
    image: mediawiki
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql
      - ./backup:/backup
    ports:
      - 3306
